Add Veracode Actions
github-technology-partners/partner-actions pull request #11
Opened 2023-11-16 20:10 UTC by mtawadrousv

### :warning: [Contribution Guidelines](contributing.md) :warning:

Thank you for your contribution! Please ensure you have followed the guidelines provided below before submitting your PR:

#### Code of Conduct

- [X] I have read and agreed to the [Contributor Code of Conduct](code-of-conduct.md).

#### Adding Your Action: Requirements

Ensure you can check all the boxes:

- [X] The organization that holds the action's source repository is a registered member of the Technology Partner Program (TPP). More about TPP [here](http://partner.github.com).
- [X] Code scanning is enabled on the repo holding the action.
- [X] Dependabot is enabled on the repo.
- [X] MFA is enabled for the maintainers of the Action.
- [X] Verified Badge for the organization that owns the Action.
- [X] Security Policy is present in the repo holding the action.

#### Ensure fields are filled correctly:

- [X] **Category**: Selected only ONE category from the list of in the [Contribution Guidelines](contributing.md).
- [X] **Partner**: Name of the organization that is registered with TPP and holds the action's source repository.
- [X] **Action**: Provided a direct hyperlink to your GitHub Action.
- [X] **Description**: Maximum of 100 characters.
- [X] **Security Policy**: Hyperlinked to the security policy in the source repo of the Action.

By submitting this PR, you acknowledge that you have checked off all boxes and followed the [contribution guidelines](contributing.md).

2023-11-17 17:27 UTC, mattlovestech requested changes

2023-11-17 17:27 UTC, mattlovestech commented on README.md
> +|Security|Veracode|[Upload & Scan](https://github.com/marketplace/actions/veracode-upload-and-scan)|Automatically scan your code using Veracode for first-party vulnerabilities|[Security Policy](https
@mtawadrousv do you mind using the repo links instead of the marketplace urls for each of the entries?

2023-11-17 23:03 UTC, mtawadrousv commented on README.md
> +|Security|Veracode|[Upload & Scan](https://github.com/marketplace/actions/veracode-upload-and-scan)|Automatically scan your code using Veracode for first-party vulnerabilities|[Security Policy](https
@mattlovestech Sorry about that - just updated

2023-11-22 14:37 UTC, mtawadrousv commented on README.md
> +|Security|Veracode|[Upload & Scan](https://github.com/marketplace/actions/veracode-upload-and-scan)|Automatically scan your code using Veracode for first-party vulnerabilities|[Security Policy](https
Hey @mattlovestech - just resolved the conflicts, let me know if you need anything else

2023-11-23 15:54 UTC, mattlovestech submitted a review, later dismissed

2023-11-23 15:55 UTC, mattlovestech commented
@mtawadrousv apologies for the delay - looks like there is a conflict now but, I approved on my end.

2023-11-23 16:02 UTC, mtawadrousv commented
Should be resolved now

2023-11-23 18:05 UTC, merged